---
title: "Assignment 2"
author: "Cody Appa"
format: html
jupyter: python3
code-fold: true
date: 02/02/2023
---

# Summary
Using digital droplet PCR data we were able to quantify the ratio of the chromosomal origin and terminus of chlamydia on a population level. Using this data we can determine whether a population is actively in the cell cycle or not.


```{python}
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import numpy as np; np.random.seed(22)
import seaborn as sns; sns.set(color_codes=True)
import pandas as pd

import math
```

```{python}
datadir = '/Users/codyappa/Documents/BCB504/BCB504Portfolio/posts/post-with-code/Sheet 2-Table 1.csv'
```

```{python}
df = pd.read_csv('Sheet 2-Table 1.csv')
```
## My Data
The data used here is counts from around 20k individual pcr reactions per timepoint isolated in lipid droplets. We then use probes that are specific to individual chromosomal regions within the origin or terminus to determine the number of each. Actively replicating chromosomes start a replication fork at the origin leading to a 2:1 origin to terminus ratio. Non-replicating chromosomes only have one origin.

```{python}
df
```

```{python}
df.describe()
```

```{python}
Attributes = pd.read_csv('Assignment2_description.csv')
```

```{python}
Attributes
```
## Plot
In order to properly visualize the ratios of three different treatments: Untreated, Induced, and Washout samples, I decided to use a violin plot. The violin plot allows for accurate visualization of ratios similar to a box and whisker plot, we then spaced out the individual treatments so that they would not overlap and cover eachother.
```{python}
with plt.style.context('seaborn-white'):
    fig, ax = plt.subplots(ncols=1)
    sns.violinplot(x=df['Hpi'], y=df['Ratio'], hue=df['Treatment'], data=df, ax=ax, dodge ="True", boxprops=dict(alpha=1),linewidth=.9, scale="width", showmeans=True)
with plt.style.context('classic'):
    ax.legend(loc='upper right', fontsize=10)
    ax.ticklabel_format( axis="y", style="sci", scilimits=(0,2))
fig.set_size_inches(4, 4)
#ax.set_yscale('symlog', linthreshy=200)
```

```{python}
plt.show()
```
# Conclusions
We concluded from this plot that each treatment follows the same trend of starting off as dividing populations and then leaving the cell cycle after 32hpi. This indicates that the cells within the population are largely non replicators such as RBs or IBs.